// Generated by CoffeeScript 1.7.1
var Checker;

Checker = (function() {
  function Checker(alert, message) {
    var _ref, _ref1;
    this.alert = alert;
    this.message = message;
    this.alert = (_ref = this.alert) != null ? _ref : true;
    this.message = (_ref1 = this.message) != null ? _ref1 : "I found it";
  }

  Checker.prototype.check = function(id) {
    var func;
    this.id = id;
    debugger;
    func = this.alert ? alert : console.log;
    if (typeof document !== "undefined" && document !== null ? document.getElementById(this.id) : void 0) {
      return func(this.message);
    }
  };

  return Checker;

})();

new Checker().check('rubbish');

new Checker().check('element1');

//# sourceMappingURL=Sample7.map
