// Generated by CoffeeScript 1.7.1
var Checker;

Checker = (function() {
  function Checker(alert, message) {
    this.alert = alert != null ? alert : true;
    this.message = message != null ? message : "I found it";
  }

  Checker.prototype.check = function(id) {
    var func;
    this.id = id;
    debugger;
    func = this.alert && (typeof alert !== "undefined" && alert !== null) ? alert : console.log;
    if (typeof document !== "undefined" && document !== null ? document.getElementById(this.id) : void 0) {
      return func(this.message);
    }
  };

  return Checker;

})();

new Checker().check('rubbish');

new Checker().check('element1');

//# sourceMappingURL=Sample7.map
