// Generated by CoffeeScript 1.7.1
(function() {
  var numbers, _ref;

  numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9];

  console.log(numbers.slice(0, 3));

  console.log(numbers.slice(3, -2));

  console.log(numbers.slice(-2));

  console.log(numbers.slice(0));

  console.log(([].splice.apply(numbers, [3, 4].concat(_ref = [-3, -4, -5, -6])), _ref));

}).call(this);

//# sourceMappingURL=Sample4.map
