// Generated by CoffeeScript 1.7.1
(function() {
  var Animal, Eagle, eagle,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Animal = (function() {
    function Animal() {}

    Animal.prototype.walk = function() {
      throw "Not yet implemented";
    };

    return Animal;

  })();

  Eagle = (function(_super) {
    __extends(Eagle, _super);

    function Eagle(name) {
      this.name = name;
    }

    Eagle.prototype.walk = function() {
      return console.log("[Eagle] I'm an eagle, my name is " + this.name + " and I can walk, walk ...");
    };

    Eagle.prototype.canFly = function() {
      return true;
    };

    return Eagle;

  })(Animal);

  eagle = new Eagle('Karl');

  eagle.walk();

  if (eagle.canFly()) {
    console.log("I can fly");
  }


  /*
   * Elvis is back, baby 
  
   *[drogs, alcohol, rockAndRoll] = [true, !!(yes * 10), on]
  
  howami = "live is cool" if drogs? and alcohol? and rockAndRoll?
  console.log "Today, upon me, #{howami ? 'it sucks'}"
   */


  /*
  	lives: (country) ->
  		if country is 'usa'
  			address:
  				street: 'White house'
  		else
  			address: 'rubbish heap'
  
  console.log "It's a big cheese eagle" if eagle.lives?('usa')?.address?.street is 'White house'
   */


  /*
   * Functions binding
  
  console.log eagle.walk.call(console)
   */


  /*
  
   * Destructuring assignment
  
  sendToJail =
  	vbCreator: "Tevin F***er"
  	tsqlGenerator:
  		name:   "Le Jacques"
  		address: [
  			"Rue de la prison 10"
  			"75010"
  			"Paris"
  			"France"
  		]
  
  {tsqlGenerator: {name, address: [street, zip, city, country]}} = sendToJail
  
  console.log "#{name} for all of your crimes against the humanity, I'll come for you to #{city} and I'll send you to the jail"
   */

}).call(this);

//# sourceMappingURL=Sample6.map
